import { SchoolType } from '../types/SchoolType';

export const schoolDB: SchoolType[] = [
  {
    id: '1',
    name: 'EMEFI Profª Áurea Cantinho Rodrigues',
    address: 'Rua Irã, 135',
    neighborhood: 'JD Oswaldo Cruz',
    latitude: -23.20035,
    longitude: -45.88289,
  },
  {
    id: '2',
    name: 'EMEFI Profª Maria Aparecida dos Santos Ronconi',
    address: 'Rua Ana Gonçalves da Cunha, 400',
    neighborhood: 'JD Jussara',
    latitude: -23.18763,
    longitude: -45.86882,
  },
  {
    id: '3',
    name: 'EMEFI Profº Felício Savastano',
    address: 'Rua Cap. Raul Fagundes, 341',
    neighborhood: 'Monte Castelo',
    latitude: -23.18282,
    longitude: -45.87289,
  },
  {
    id: '4',
    name: 'EMEFI Dr. Maurício Anisse Cury',
    address: 'Av. Eng. Francisco José Longo, 832',
    neighborhood: 'Jd São Dimas',
    latitude: -23.20033,
    longitude: -45.88877,
  },
  {
    id: '5',
    name: 'EMEFI Profª Suely Antunes de Mello',
    address: 'Rua Siqueira Campos, 845',
    neighborhood: 'Centro',
    latitude: -23.17854,
    longitude: -45.87801,
  },
  {
    id: '6',
    name: 'EMEFI Profº Antônio Palma Sobrinho',
    address: 'Rua Ângelo Scarpel, 163',
    neighborhood: 'Pq. Nova Esperança',
    latitude: -23.20094,
    longitude: -45.78399,
  },
  {
    id: '7',
    name: 'EMEFI Profª Elizabete de Paula Honorato',
    address: 'Rua Aurélio Portilho Castellanos, 124',
    neighborhood: 'JD Mariana I',
    latitude: -23.21327,
    longitude: -45.80173,
  },
  {
    id: '8',
    name: 'EMEFI Profº Geraldo de Almeida',
    address: 'Rua Camomila, 100',
    neighborhood: 'Chac. Pousada do Vale',
    latitude: -23.22192,
    longitude: -45.79309,
  },
  {
    id: '9',
    name: 'EMEFI Profº Hélio Augusto de Souza',
    address: 'Praça dos Músicos, s/n',
    neighborhood: 'JD Valparaíba',
    latitude: -23.17487,
    longitude: -45.84208,
  },
  {
    id: '10',
    name: 'EMEFI Profª Ilga Pusplatais',
    address: 'Uberlândia, 465',
    neighborhood: 'JD Ismênia',
    latitude: -23.17543,
    longitude: -45.84704,
  },
  {
    id: '11',
    name: 'EMEFI Profª Leonor Pereira Nunes Galvão',
    address: 'Rua José Molina, 150',
    neighborhood: 'Vila Industrial',
    latitude: -23.17954,
    longitude: -45.85854,
  },
  {
    id: '12',
    name: 'EMEFI Profº Luiz Leite',
    address: 'Rua Benedito Andrade, 5',
    neighborhood: 'Res. Galo Branco',
    latitude: -23.13173,
    longitude: -45.76558,
  },
  {
    id: '13',
    name: 'EMEFI Profª Luiza Maria Cavalcanti Guratti',
    address: 'Rua Benedita Francisca da Rosa, 203',
    neighborhood: 'Lot. Setville Altos de São José',
    latitude: -23.22464,
    longitude: -45.81967,
  },
  {
    id: '14',
    name: 'EMEFI Profª Maria Amélia Wakamatsu',
    address: 'Rua Virgílio Fernandes de Oliveira, 31',
    neighborhood: 'Campos de São José',
    latitude: -23.20981,
    longitude: -45.80947,
  },
  {
    id: '15',
    name: "EMEFI Profª Palmyra Sant'anna",
    address: 'Rua Prof. Felício Savastano, 350',
    neighborhood: 'Vila Industrial',
    latitude: -23.18302,
    longitude: -45.85834,
  },
  {
    id: '16',
    name: 'EMEFI Profº Possidônio José de Freitas',
    address: 'Rua Felício Jabur Nasser, 935',
    neighborhood: 'Res. Galo Branco',
    latitude: -23.13631,
    longitude: -45.77438,
  },
  {
    id: '17',
    name: 'EMEFI Profº Possidônio Salles',
    address: 'Rua Benedito Eras, s/n',
    neighborhood: 'Jd. Americano',
    latitude: -23.17924,
    longitude: -45.81211,
  },
  {
    id: '18',
    name: 'EMEFI Profª Rosa Tomita',
    address: 'Rua Ayrton senna da Silva, 90',
    neighborhood: 'Jd São José II',
    latitude: -23.17031,
    longitude: -45.77853,
  },
  {
    id: '19',
    name: 'EMEFI Profª Silvana Maria Ribeiro de Almeida',
    address: 'Rua 4 de Março, 10',
    neighborhood: 'Jd das Cerejeiras',
    latitude: -23.19423,
    longitude: -45.79278,
  },
  {
    id: '20',
    name: 'EMEFI Profª Sônia Maria Pereira da Silva',
    address: 'Rua dos Alfaiates, 321',
    neighborhood: 'Pq Novo Horizonte',
    latitude: -23.19805,
    longitude: -45.78149,
  },
  {
    id: '21',
    name: 'EMEFI Profª Terezinha Araujo',
    address: 'Rua Pedra do Sol, 1700',
    neighborhood: 'Jd Santa Hermínia',
    latitude: -23.21137,
    longitude: -45.77965,
  },
  {
    id: '22',
    name: 'EMEFI Profº Waldemar Ramos',
    address: 'Rua México, 84',
    neighborhood: 'Vista Verde',
    latitude: -23.18219,
    longitude: -45.83143,
  },
  {
    id: '23',
    name: 'EMEFI Emmanuel Antônio dos Santos',
    address: 'Rua das Cerejas, 150',
    neighborhood: 'Res. Frei Galvão',
    latitude: -23.16814,
    longitude: -45.78934,
  },
  {
    id: '24',
    name: 'EMEFI Profª Adélia Chucri Neme',
    address: 'Av. Pres. Juscelino Kubitschek, 6701',
    neighborhood: 'Vila Industrial (Integração)',
    latitude: -23.18254,
    longitude: -45.86054,
  },
  {
    id: '25',
    name: 'EMEFI Profª Amintas Rocha Brito',
    address: 'Rua Aníbal Ferri, 193',
    neighborhood: 'Jd. Castanheira',
    latitude: -23.1851,
    longitude: -45.79282,
  },
  {
    id: '26',
    name: 'EMEFI Profª Arlete Eloíza Ferreira Teixeira',
    address: 'Rua Orlando Silva, 85',
    neighborhood: 'Jd. Nova Detroit',
    latitude: -23.16647,
    longitude: -45.811,
  },
  // {
  //   id: '23',
  //   name: 'EMEFI Emmanuel Antônio dos Santos',
  //   address: 'Rua das Cerejas, 150',
  //   neighborhood: 'Res. Frei Galvão',
  //   latitude: -23.16814,
  //   longitude: -45.7894,
  // },
];
